#!/bin/busybox sh

mount -t proc none /proc
mount -t sysfs none /sys

/bin/busybox --install -s 2>/dev/null

# populate /dev
mknod /dev/null c 1 3
mknod /dev/tty c 5 0

mdev -s

mount /dev/mmcblk0p2 /rootfs

if [ $(cat /proc/cmdline | grep splash | wc -l) -eq 1 ]; then
	if [ -f "/rootfs/usr/bin/splash" ]; then
		if [ -f "/rootfs/var/splash.pid" ]; then
			rm /rootfs/var/splash.pid;
		fi
		if [ -f "/rootfs/var/splash.dat" ]; then
			rm /rootfs/var/splash.dat;
		fi
	        $(/rootfs/usr/bin/splash --percentage=12);
	fi
fi

sleep 1;

umount /proc
umount /sys

exec switch_root /rootfs /sbin/init

echo "Failed to switch_root, dropping to a shell"
exec /bin/sh
