#!/bin/busybox sh

mount -t proc none /proc
mount -t sysfs none /sys

/bin/busybox --install -s 2>/dev/null

# populate /dev
mknod /dev/tty c 5 0

mdev -s

ROOTDEV="/dev/mmcblk0p2";
ROOTFSTYPE="ext4";
ROOTFSOPTS="noatime";
SPLASH=0;
RESIZEERROR=0;
INITIALBOOT=0;
NORESIZESD="0"
NOSWAPFILE="0"

# read cmdline config
ARRAY=`sed -e '/^#/d' /proc/cmdline | sed -e 's/ /\n/g' | while read line; do
        if [ ! -z ${line} ]; then
                if [ $(echo ${line} | grep "=" | wc -l) -eq 1 ]; then
                        name=${line%%=*};
                        name=${name/./_};
                        echo ${name}="${line##*=}";
                else
	                name=${line/./_};
                        echo ${name}="1";
                fi
        fi
done;`

for line in ${ARRAY}; do
	case ${line%%=*} in
		root)
			ROOTDEV=${line##*=};
		;;
		rootfstype)
			ROOTFSTYPE=${line##*=};
		;;
		rootfsopts)
			ROOTFSOPTS=${line##*=};
		;;
		splash)
			SPLASH=${line##*=}
		;;
		noresizesd)
			NORESIZESD=${line##*=}
		;;
		noswapfile)
			NOSWAPFILE=${line##*=}
		;;
	esac
done

# check if new root partition exists
X=0;
while [ ! -b "${ROOTDEV}" ] && [ ${X} -lt 10 ]; do
	X=$(($X+1));
	mdev -s
	sleep 1;
done;

if [ ! -b "${ROOTDEV}" ]; then
	echo "Root partition ${ROOTDEV} missing"
	exec /bin/busybox sh
	exit 0
fi 

# resize root partition
if [ "${ROOTDEV}" == "/dev/mmcblk0p2" ] && [ ${NORESIZESD} == "0" ]; then

	#Save partition table to file
	/sbin/sfdisk -d /dev/mmcblk0 > /tmp/curpart.txt

	#Backup partition table
	cp /tmp/curpart.txt /tmp/part.txt

	#Read partition sizes
	TOTALBLOCKS=`/sbin/fdisk -l /dev/mmcblk0 | grep total | awk '{printf "%s", $8}'`;
	LASTBLOCK=$TOTALBLOCKS;
	PARTSTART=`grep Id=83 /tmp/part.txt | awk '{printf "%d", $4}'`;
	PARTSIZE=`grep Id=83 /tmp/part.txt | awk '{printf "%d", $6}'`;
	NEWSIZE=$(($LASTBLOCK-$PARTSTART));

	if [ $PARTSIZE -lt $NEWSIZE ]; then
		#Change size of root partition
		sed -i "s/$PARTSIZE/$NEWSIZE/g" /tmp/part.txt

		#Backup current partition
		/sbin/sfdisk --no-reread -q -f /dev/mmcblk0 -O /tmp/part.bin < /tmp/part.txt &> /dev/null

		#Dump new partition
		/sbin/sfdisk -d /dev/mmcblk0 > /tmp/newpart.txt

		#Check if the changes could be made to the partition table
		CHECKSIZE=`grep Id=83 /tmp/newpart.txt | awk '{printf "%d", $6}'`;

		if [ $CHECKSIZE -ne $NEWSIZE ]; then
			#If partition table could not be changed
			DIFF=`diff /tmp/curpart.txt /tmp/newpart.txt; echo $?`
			if [ ${DIFF} != "0" ]; then
				#Restoring old partition table
				/sbin/sfdisk --force -q -I /tmp/part.bin /dev/mmcblk0 &> /dev/null
			fi
			RESIZEERROR=1;
		fi
	fi
fi

# mount root partition
mount -t ${ROOTFSTYPE} -o rw,${ROOTFSOPTS} ${ROOTDEV} /rootfs
if [ $? -ne 0 ]; then
	echo "Mounting root partition ${ROOTDEV} failed"
	exec /bin/busybox sh
	exit 0
fi

# display splash
if [ ${SPLASH} == "1" ]; then
	if [ -f "/rootfs/usr/bin/splash" ]; then
		if [ -f "/rootfs/var/splash.pid" ]; then
			rm /rootfs/var/splash.pid;
		fi
		if [ -f "/rootfs/var/splash.dat" ]; then
			rm /rootfs/var/splash.dat;
		fi
	fi
fi

# check if we are in the initialboot
if [ -f /rootfs/root/initialboot ]; then
	INITIALBOOT=1;
	rm /rootfs/root/initialboot;
	if [ ${SPLASH} == "1" ]; then
		/rootfs/usr/bin/splash --infinitebar --msgtxt="initial setup...";
	fi
fi

if [ "${ROOTDEV}" == "/dev/mmcblk0p2" ] && [ $RESIZEERROR -eq 0 ] && [ ${NORESIZESD} == "0" ]; then
	# check if the partition needs resizing
	FDISKBLOCKSIZE=`/sbin/sfdisk -d /dev/mmcblk0 | grep Id=83 | awk '{printf "%d", $6}'`
	FDISKBLOCKCOUNT=`/sbin/fdisk -l /dev/mmcblk0 | grep Units | sed -ne 's/\(.*= \)\([0-9]\{1,\}\)\( bytes\)/\2/p'`
	TUNE2FS=`/sbin/tune2fs -l /dev/mmcblk0p2`
	TUNEBLOCKSIZE=`echo -e "${TUNE2FS}" | grep "Block size" | awk '{printf "%d", $3}'`
	TUNEBLOCKCOUNT=`echo -e "${TUNE2FS}" | grep "Block count" | awk '{printf "%d", $3}'`
	TUNETOTALBLOCKS=$(($(($TUNEBLOCKCOUNT*$TUNEBLOCKSIZE))/1024/1024));
	FDISKTOTALBLOCKS=$(($(($FDISKBLOCKSIZE*$FDISKBLOCKCOUNT))/1024/1024));
		
	# resize root partition
	if [ ${TUNETOTALBLOCKS} -lt ${FDISKTOTALBLOCKS} ]; then
		if [ ${SPLASH} == "1" ]; then
			if [ $INITIALBOOT -eq 0 ]; then
				/rootfs/usr/bin/splash --infinitebar --msgtxt="resizing sd...";
			fi
			/rootfs/sbin/resize2fs ${ROOTDEV}
		else
echo '
8888888b.  8888888888  .d8888b.  8888888 8888888888P 8888888 888b    888  .d8888b.
888   Y88b 888        d88P  Y88b   888         d88P    888   8888b   888 d88P  Y88b
888    888 888        Y88b.        888        d88P     888   88888b  888 888    888
888   d88P 8888888     "Y888b.     888       d88P      888   888Y88b 888 888
8888888P"  888            "Y88b.   888      d88P       888   888 Y88b888 888  88888
888 T88b   888              "888   888     d88P        888   888  Y88888 888    888
888  T88b  888        Y88b  d88P   888    d88P         888   888   Y8888 Y88b  d88P
888   T88b 8888888888  "Y8888P"  8888888 d8888888888 8888888 888    Y888  "Y8888P88';
			/rootfs/sbin/resize2fs;
		fi
	fi

	FDISKBLOCKSIZE=`/sbin/sfdisk -d /dev/mmcblk0 | grep Id=83 | awk '{printf "%d", $6}'`
	FDISKBLOCKCOUNT=`/sbin/fdisk -l /dev/mmcblk0 | grep Units | sed -ne 's/\(.*= \)\([0-9]\{1,\}\)\( bytes\)/\2/p'`
	TUNE2FS=`/sbin/tune2fs -l /dev/mmcblk0p2`
	TUNEBLOCKSIZE=`echo -e "${TUNE2FS}" | grep "Block size" | awk '{printf "%d", $3}'`
	TUNEBLOCKCOUNT=`echo -e "${TUNE2FS}" | grep "Block count" | awk '{printf "%d", $3}'`
	TUNETOTALBLOCKS=$(($(($TUNEBLOCKCOUNT*$TUNEBLOCKSIZE))/1024/1024));
	FDISKTOTALBLOCKS=$(($(($FDISKBLOCKSIZE*$FDISKBLOCKCOUNT))/1024/1024));

	# check if parition was actually resized
	if [ ${TUNETOTALBLOCKS} -lt ${FDISKTOTALBLOCKS} ]; then
		RESIZEERROR=1
	fi	
fi

# create swapfile
if [ ! -f /rootfs/var/swapfile ] && [ $RESIZEERROR -eq 0 ] && [ ${NOSWAPFILE} == "0" ]; then
	if [ ${SPLASH} == "1" ]; then
		if [ $INITIALBOOT -eq 0 ]; then
			/rootfs/usr/bin/splash --infinitebar --msgtxt="creating swapfile...";
		fi
		dd if=/dev/zero of=/rootfs/var/swapfile bs=1024 count=128000
	else
echo '
       d8888 8888888b.  8888888b.     .d8888b.  888       888        d8888 8888888b.  
      d88888 888  "Y88b 888  "Y88b   d88P  Y88b 888   o   888       d88888 888   Y88b 
     d88P888 888    888 888    888   Y88b.      888  d8b  888      d88P888 888    888 
    d88P 888 888    888 888    888    "Y888b.   888 d888b 888     d88P 888 888   d88P 
   d88P  888 888    888 888    888       "Y88b. 888d88888b888    d88P  888 8888888P"  
  d88P   888 888    888 888    888         "888 88888P Y88888   d88P   888 888        
 d8888888888 888  .d88P 888  .d88P   Y88b  d88P 8888P   Y8888  d8888888888 888        
d88P     888 8888888P"  8888888P"     "Y8888P"  888P     Y888 d88P     888 888';
		dd if=/dev/zero of=/rootfs/var/swapfile bs=1024 count=128000
	fi
	/sbin/mkswap /rootfs/var/swapfile &>/dev/null
	/sbin/swapon /rootfs/var/swapfile &>/dev/null
fi

# add swapfile to fstab
if [ -f /rootfs/var/swapfile ]; then
	IFSWAP=`grep /var/swapfile /rootfs/etc/fstab | wc -l`
	if [ ${IFSWAP} == "0" ]; then
		echo -e '/var/swapfile\tswap\tswap\tdefaults\t0\t0' >> /rootfs/etc/fstab
	fi
fi

# continue with normal boot
if [ ${SPLASH} == "1" ]; then
	/rootfs/usr/bin/splash --percentagebar --percentage=12 --msgtxt="loading...";
	# give splash time to settle
	sleep 1;
fi

umount /proc
umount /sys

exec switch_root /rootfs /sbin/init

echo "Failed to switch_root, dropping to a shell"
exec /bin/busybox sh
