#!/bin/bash

if [ $1 == "install" -o $1 == "upgrade" ]; then
    [ -e /etc/default/xbian-initramfs ] && \
        { sed -i 's/WLAN=/LAN=/g' /etc/default/xbian-initramfs; mv /etc/default/xbian-initramfs /etc/default/xbian-initramfs.preinst; } || :
fi
