#!/bin/bash

if [ $1 == "configure" ]; then

        mountpoint -q /boot || mount /boot
        /etc/xbian-initramfs/update-initramfs.sh > /dev/null 2>&1
        cat /boot/config.txt | grep -v initramfs.gz > /boot/config.txt.new
        echo "initramfs initramfs.gz  0x00a00000" > /boot/config.txt
        cat /boot/config.txt.new >> /boot/config.txt
        rm /boot/config.txt.new
        umount /boot

fi
