#!/bin/bash

if [ $1 == "configure" ]; then

	echo $(date) >> /home/xbian/xbian-initramfs-update.log

        mountpoint -q /boot || mount /boot
        /etc/xbian-initramfs/update-initramfs.sh > /dev/null 2>&1
        cat /boot/config.txt | grep -v initramfs.gz > /boot/config.txt.new
        echo "initramfs initramfs.gz  0x00a00000" > /boot/config.txt
        cat /boot/config.txt.new >> /boot/config.txt
        rm /boot/config.txt.new
        umount /boot

	echo "Disabling system initramfs-update process" >> /home/xbian/xbian-initramfs-update.log
	if [ $(grep -c "update_initramfs=no" /etc/initramfs-tools/update-initramfs.conf) -eq '1' ];
	then
		echo "Already diasbled" >> /home/xbian/xbian-initramfs-update.log
	else
		sed 's/update_initramfs=yes/update_initramfs=no/' /etc/initramfs-tools/update-initramfs.conf \
			> /etc/initramfs-tools/update-initramfs.conf.new
		if [ $(grep -c "update_initramfs=no" /etc/initramfs-tools/update-initramfs.conf.new) -eq '1' ];
		then
			echo "Disabled successfully" >> /home/xbian/xbian-initramfs-update.log
			mv /etc/initramfs-tools/update-initramfs.conf.new /etc/initramfs-tools/update-initramfs.conf
		else
			echo "ERROR disabling system initramfs-update process" >> /home/xbian/xbian-initramfs-update.log
		fi
	fi

        echo "---UPDATE LOG---"
        cat "/home/xbian/xbian-initramfs-update.log"

fi

