#!/bin/sh
grep -q BCM2708 /proc/cpuinfo && platform='RPI'
grep -q BCM2709 /proc/cpuinfo && platform='RPI2'
grep -q sun7i /proc/cpuinfo && platform='BPI'
grep -q "Freescale i.MX6" /proc/cpuinfo && platform='iMX6'
grep -q "SolidRun i.MX6" /proc/cpuinfo && platform='iMX6'
grep -q "HummingBoard" /proc/cpuinfo && platform='iMX6'
grep -q "SolidRun Cubox-i" /proc/cpuinfo && platform='iMX6'

[ -z "$platform" ] && platform='unknown'

echo "$platform"
