#!/bin/sh

if [ "$#" != '1' ]; then
	echo "Usage: xbian-resize block-device [UUID=] [[LABEL=]]"
	echo
	echo " block-device must be special file in the form \"/dev/sda2\""
	echo "    instead of block-device, you can specify"
	echo "        UUID=xxxxxxxxxxx or LABEL=label"

	exit 1
fi

export CONFIG_root="$1"
export RESIZEERROR='0'
export CONFIG_noresizesd='0'

. /etc/xbian-initramfs/cnvres-code.sh

get_root

resize_part

